### ISSUE TITLE
Settings Apply fails

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/views_accordion#10]
When saving the Settings immediately after adding the Views Accordion type, there is a 500 server error thrown. This is not thrown for other Views settings, eg HTML list.
On PHP 8.1.26 FPM, nGinx, Ubuntu 22.04

**Comment by laryn** [comment]
@onyxnz Thanks for the report. It looks like I missed another report some months back. Can you test and see if they are the same issue? There is a fix suggestion listed here: https://github.com/backdrop-contrib/views_accordion/issues/9

If that works I can make a new release.

**Comment by onyxnz** [comment]
Very good, that fixed it.

**Comment by laryn** [comment]
@onyxnz Would you be willing to submit that fix as a PR that I can merge?

**Comment by onyxnz** [comment]
> @onyxnz Would you be willing to submit that fix as a PR that I can merge?

Sorry, man, cannot figure out how to...the git help says that I need to create off another branch, but there isn't one? Should I be creating another repo on my own account then doing the PR from there?

**Comment by laryn** [comment]
Fixed in https://github.com/backdrop-contrib/views_accordion/issues/9
