### ISSUE TITLE
Improvements to ReadMe

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_accordion#11]
Some minor suggestions to improve the README. 

![image](https://github.com/backdrop-contrib/views_accordion/assets/3144571/9156eac2-9d28-49e0-950e-90d0f718ceb9)

I think it would be better to use the words "Format" and "Show", which are the visible labels for the fields being set, rather than referring to them as "row style" in the "style dialog". Both are accurate, but not what the person is seeing.

If I can come up with any other improvements, I'll add them later.

CURRENT README (before PR):

![image](https://github.com/user-attachments/assets/e0bb652e-f63d-427b-9d7f-c9b83e2cd0c4)

**Comment by laryn** [comment]
@stpaultim Good idea to clarify these. Can you put the "Show: Fields" section first? Part of the settings for the "Format: Views Accordion" section involves selecting fields that should be set as a first step, if I recall correctly.

EDIT: If I'm wrong, feel free to ignore that and let me know. I may be confusing this with another module.

**Comment by stpaultim** [comment]
@laryn Here is screen shot of changes

![image](https://github.com/user-attachments/assets/77e61afc-a2d7-4bfa-a1e8-783dd3fc3aaa)

I think this accurately describes the process. In fact, one is not required to make any field selection in the format settings. The module automatically assumes "the first field WILL be used as the header for each accordion section, all others will be displayed when the header is clicked."

![image](https://github.com/user-attachments/assets/c85c621c-2e21-4fde-913e-fba0e7edf919)

**Comment by laryn** [comment]
Thanks @stpaultim!
