### ISSUE TITLE
Enhanced navigation anchors

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/views_accordion#2]
As per the [Drupal equivalent issue](https://www.drupal.org/project/views_accordion/issues/1127224) it'd be good to have row IDs that can be used for navigation, not just based on the position of the row in the view.

PR: https://github.com/backdrop-contrib/views_accordion/pull/3

**Comment by laryn** [comment]
@BWPanda Have you been using this patch without issue? I notice the Drupal issue is still labelled as "Needs work".

**Comment by ghost** [comment]
Yes, you can see it in action here: https://www.takemeoutsidensw.org.au/ - scroll down to 'Project Ideas' then click an item to open that accordion section on the resulting page.

The 'Needs Work' tag in Drupal seems to be due to a deprecated part of jQueryUI, but I can't see how this patch is affected by that, and on the site I linked above I'm using jQueryUI 1.12.x and it seems to work fine...

**Comment by laryn** [comment]
@BWPanda 
I see it working on your site (nice site btw), but when I test locally, the "deep links" don't seem to open in that way. Do you mind sharing your View display settings so I can test again (and include in a Wiki page for others who may want this)?

**Comment by ghost** [comment]
Ah, it seems I added this jQuery to my theme:

```js
(function($) {
Backdrop.behaviors.accordion = {
  attach: function(context, settings) {
    $('.views-view-accordion .views-accordion-header').has('a[href$="' + location.hash + '"]').click();
  }
};
})(jQuery);
```

**Comment by laryn** [comment]
@BWPanda If there's an easy way to combine this into the module's existing JS so this functionality works out of the box I think it would be a good addition. I tried just inserting:

`$('.views-view-accordion .views-accordion-header').has('a[href$="' + location.hash + '"]').click();`

into the current JS but the body of the accordion disappeared (although deep linking worked). Are you able to revise your PR?

**Comment by laryn** [comment]
No I take it back, that may have just been some strange combination of settings as I was testing another issue that had been reported. This may work...

**Comment by laryn** [comment]
@BWPanda Can you spot check this and see if it looks reasonable? I tried to merge your JS into the module's JS and reformatted slightly.
https://github.com/backdrop-contrib/views_accordion/pull/3/commits/78ed98747d9f8714c297e855c1f22a02cb2cba2b

**Comment by ghost** [comment]
I think so... I mean, my JS-foo isn't very good; I tend to just copy-paste without knowing exactly how stuff works. So if it works then great! :+1:

**Comment by laryn** [comment]
Thanks @BWPanda I've merged this functionality.
