### ISSUE TITLE
Filtering by Content Title = "Title of Content" not working

### ISSUE THREAD

**Issue by TheMetMan** [backdrop-contrib/views_accordion#4]
I have created an Accordion using the Title and Body which works fine when Filtered for All Published Content or Content Type, but filtering by Content Title = "Title of Content" (I only want three pages) does not work.

**Comment by laryn** [comment]
Thanks @TheMetMan -- can you paste a screenshot of the View and the End result?

**Comment by TheMetMan** [comment]
Thanks for the quick response, @laryn I have solved the problem by creating a Content Type which only contains the content I want to display in the Accordion, so all is well now.
If you would still like me to recreate the problem with Screenshots, I would be delighted to do so

**Comment by laryn** [comment]
@TheMetMan If you have some spare time feel free and I will eventually look at it, but it might be a while, especially since you have a solution in place.

**Comment by TheMetMan** [comment]
Here is the Screenshot as promised. I have the 'Auto Preview' checked which just shows the title of the view with no content. If I open the page 'test-accordion' in the browser I just get the View Title.
![ViewScreenshot20191113](https://user-images.githubusercontent.com/6077253/68757549-06af2980-0604-11ea-8386-0da19d1bc85a.png)

**Comment by TheMetMan** [comment]
Sorry @laryn clicked the 'Close and Comment' instead of 'Comment' by mistake.

**Comment by laryn** [comment]
@TheMetMan It looks like the filter criteria can never be met since no content has all three of those titles, right?

**Comment by TheMetMan** [comment]
Of course!!!, @laryn I will change the logic.

**Comment by TheMetMan** [comment]
Mmmm... There is no way to AND or OR in the logic, so it would be necessary to have something common to all three pages to be able to have all three showing up.
Never mind. I understand why it does not work, and my method of using a dedicated Content Type Works.
Do I close this or do you @laryn ?

**Comment by laryn** [comment]
@TheMetMan If you click the little down arrow to the right of "Add" (in the Filter Criteria section) you should find a way to implement AND/OR groupings.
