### ISSUE TITLE
Fill Space not working on Page refresh

### ISSUE THREAD

**Issue by TheMetMan** [backdrop-contrib/views_accordion#5]
I am using latest Backdrop with latest views_accordion. I have a title and an image in each accordion. In the Views Accordion Settings I have unchecked the Autoheight, and checked the Fill space and Clear Style.
When I go to the page using a link all is well, the image is shown, but if I refresh the page with the browser, the image is only partly displayed with a scroll bar. When I click the link again from the breadcrumb or menu it displays normally.
Why is that happening?

**Comment by laryn** [comment]
@TheMetMan Anything in the JS console? Are you able to show a screenshot?

**Comment by TheMetMan** [comment]
This morning I discovered I only seem to have the problem on my own PC running Firefox in Gentoo Linux I have looked at it with Linux Mint and it is OK. Perhaps have a look at https://themetman.net to see if it is OK for you. It is probably some strange Gentoo thing.
![normal](https://user-images.githubusercontent.com/6077253/79202927-d1646d00-7e29-11ea-9d54-cf963bc2ee59.jpg)
![problem](https://user-images.githubusercontent.com/6077253/79202931-d2959a00-7e29-11ea-9a7e-45162b02cf08.jpg)

**Comment by laryn** [comment]
I'm not seeing that on your site or in my testing when I load a page or do a hard refresh. Let me know if you can find any more details on how to replicate the issue.

**Comment by TheMetMan** [comment]
OK, I think it must be an odd problem with my home machine, so not an issue with views_accordion, so I am happy to close it.

**Comment by laryn** [comment]
Sounds good -- reopen if needed.
