### ISSUE TITLE
Empty tests files causes issues

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/views_accordion#7]
I had downloaded a copy of this module on my local sandbox, and when I went to run tests (for another module) I was getting a bunch of errors. I narrowed them down to this module. It seems that Backdrop automatically writes to info files with the date downloaded, version number, etc., and this was being picked up by Simpletest but causing errors.

I think the easy solution is the delete the `/tests` directory since it's obviously not being used.

**Comment by laryn** [comment]
Yes, strange -- I would think we can take that out.
