### ISSUE TITLE
Errors on PHP 8

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/views_accordion#9]
From: https://forum.backdropcms.org/forum/error-views-accordion

**Steps to reproduce**
1. Fresh install with PHP 8
2. Install Views Accordion
3. Create a View and in format select accordion
4. try to save this view

**Expected result**
View saves

**Actual result**
You can´t save the View, now when visit the report page it shows this

""TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "views_element_validate_integer" not found or invalid function name in _form_validate() (line 1497 of /public_html/test/core/includes/form.inc).""

Tested in 1.24.2, 1.25.0 and 1.25.1 with the same results.

Downgrading to 7.4 fixed the issue for this user, which suggests the module needs a bit of PHP 8 attention.

**Comment by argiepiano** [comment]
That function `views_element_validate_integer ` was removed from Backdrop's Views in favor of using `'type' => 'number'`, which provides that validation in the browser. 

So, Views Accordion should change the following in file `views_accordion_style_plugin.inc`

```php
$form['animation_time'] = [
      '#type' => 'textfield',
      '#title' => t('Animation time'),
      '#default_value' => $this->options['animation_time'],
      '#description' => t('The animation duration in milliseconds'),
      '#element_validate' => array('views_element_validate_integer'),
    ];  
```

TO:

```php
$form['animation_time'] = [
      '#type' => 'number',
      '#title' => t('Animation time'),
      '#default_value' => $this->options['animation_time'],
      '#description' => t('The animation duration in milliseconds'),
    ];  
```

**Comment by olafgrabienski** [comment]
I've also encountered the issue, on a site with PHP 8.1.28. After applying the ~~PR~~ (**edit:** the fix above), the error went away, and I was able to save a view with Accordion format.

**Comment by laryn** [comment]
Thanks all, I'm adding the fix above, with an addition to indicate it needs to be a positive integer: 
  `'#min' => 0,`
